### ISSUE TITLE
Documentation could be more accurate on some points

### ISSUE THREAD

**Issue by lansolo99** [mattmilburn/strapi-plugin-preview-button#11]
Hi, great plugin 👍, easygoing instructions, but maybe you should precise a couple of things, as some of us are just starting out with v4 (I struggled with these at first): 

- Precise the configuration snippet has to be place inside a `plugin.js` file under the `config` folder.
- Precise we have to rebuild the admin first before seeing changes (you used the development mode from your screenshot, but it’s likely we’ll just use the normal dev mode).
- Precise we need to toggle the `publicationState` API parameter to `preview` when querying the content, otherwise, the draft will never be part of the response.

**Comment by lansolo99** [comment]
Also, not related to the issue but, unless I am mistaken, I noticed it's not working for single types, only collection types, right?

**Comment by forntoh** [comment]
> Precise we need to toggle the publicationState API parameter to preview when querying the content, otherwise, the draft will never be part of the response.

What do you mean? How do I do this?
Thanks

**Comment by lansolo99** [comment]
The "publicationState" parameter is part of the [Strapi API](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html#publication-state). 

If we want to get the draft version from the api response, it's mandatory to set it to "preview".
As we don't want to get the enabled all the time, I guess we should use a conditional depending if we are on a preview state or not.  Eg:

```
const postRes = await fetchAPI('/post', {
    publicationState: context.preview ? 'preview' : 'live',
    /// ...
```

**Comment by mpagels** [comment]
The documentation needs a revision. Unfortunately, there are missing crucial information. E.g. where to place the config file?

**Comment by mattmilburn** [comment]
> Also, not related to the issue but, unless I am mistaken, I noticed it's not working for single types, only collection types, right?

Correct, but check again 🙂. The plugin has very recently been updated to support single types 👍🏻

**Comment by mattmilburn** [comment]
When it comes to configuring a plugin in Strapi, I did not include those specific details in the plugin README because those guides can already be found in the Strapi docs - https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/plugins.html

This plugin does not have a public API so if you are querying the API for draft/live versions, that is not related to the functionality of this plugin. Details on querying draft/live states can be found in the Strapi docs - https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html

**Comment by lansolo99** [comment]
@mattmilburn I have tested the latest version and successfully used it for a single type, so thanks for this important support! 👍

Regarding the install instructions, nothing mandatory of course but I think it's never too much to precise things, especially as v4 is still relatively new in the game.

Here are some examples found across other marketplace plugins:

<img width="500" alt="Screenshot 2022-03-27 at 19 00 45" src="https://user-images.githubusercontent.com/10405016/160292449-cdca8d23-e40d-4d65-bfae-0581bdfce609.png">

<img width="500" alt="Screenshot 2022-03-27 at 19 01 12" src="https://user-images.githubusercontent.com/10405016/160292464-c68b303b-2b1e-4a01-b6e3-276d14381704.png">

Same for regarding draft/live, nothing mandatory but it helps and avoid potential struggles to have this check in mind before using the package.

I close the issue as it's not critical, all the best for this package!

**Comment by jpcmf** [comment]
Documentation absolutely confused to implement. Any other guide to follow? Thank you.

**Comment by jonathan-chin** [comment]
> This plugin does not have a public API so if you are querying the API for draft/live versions, that is not related to the functionality of this plugin. Details on querying draft/live states can be found in the Strapi docs - https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html

thanks @mattmilburn I'm still very new to Strapi. I thought that everything could be done via GraphQL but it seems getting draft content can only be done on REST. I wish I read this 3 days ago :)
