### ISSUE TITLE
Node 20

### ISSUE THREAD

**Issue by broksonic21** [mattmilburn/strapi-plugin-preview-button#115]
Node 20 is LTS now - but the engines in strapi-plugin-preview-button@2.1.1 is restricted to Node 20. Possible to update package.json and release a version today?

**Comment by mattmilburn** [comment]
Hi @broksonic21 Thank you for raising this issue because I did not notice that update in the latest Strapi versions 🙌🏻  I'll update this in a new release very soon and ping this issue with the update. 👍🏻

**Comment by mattmilburn** [comment]
Hi again @broksonic21 This should be fixed now in the latest [version 2.2.0](https://github.com/mattmilburn/strapi-plugin-preview-button/releases/tag/v2.2.0) of this plugin 🎉  Let me know how it goes for you 👍🏻

**Comment by broksonic21** [comment]
Looks great @mattmilburn  - thanks!
