### ISSUE TITLE
Not compatible with richtext

### ISSUE THREAD

**Issue by trungnouden1108** [mattmilburn/strapi-plugin-preview-button#117]
- Version: 2.1.1
- Description bug:
   -  When the contentType have [CKedtior richtext](https://market.strapi.io/plugins/@_sh-strapi-plugin-ckeditor). The draft and live view button are not display.
   - I debugged and found out that the error was due to this line of code **encodeURIComponent(decodeURIComponent(val))** in the **parse_url** function.
   - **Note**: Using default richtext strapi is also got this error
   
![image](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/55272632/714e968e-dd03-41b4-bac8-86894949c120)

- Please help me to take a look this issue. Thank you!

**Comment by mattmilburn** [comment]
@trungnouden1108 I'm still unable to reproduce this. What does the config for preview button found in `config/plugins.js` look like? It seems whatever URL is being passed to `decodeURIComponent` is an invalid URL format.

**Comment by mattmilburn** [comment]
@trungnouden1108 You may also want to try installing the latest [version 2.2.0](https://github.com/mattmilburn/strapi-plugin-preview-button/releases/tag/v2.2.0) of this plugin which just released yesterday. Not sure if it relates to your problem but try using Strapi v4.14.x with v2.2.0 of this plugin and let me know how it goes for you 👍🏻

**Comment by trungnouden1108** [comment]
> @trungnouden1108 I'm still unable to reproduce this. What does the config for preview button found in `config/plugins.js` look like? It seems whatever URL is being passed to `decodeURIComponent` is an invalid URL format.

![image](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/55272632/07ed2113-ee5a-4e49-bbb5-926e295f0f8d)

I have debugged and see that your code will decode and then encode the value of the entire field. And when any field has this '**%**' character, the code will error


You can create content-type contains rich-text field, and paste the content below
`- 200 grams of broccoli can provide up to 75% of the body's vitamin A needs. Glutathione transferase in improved cotton has detoxifying and fat-reducing effects`

**Comment by trungnouden1108** [comment]
> @trungnouden1108 I'm still unable to reproduce this. What does the config for preview button found in `config/plugins.js` look like? It seems whatever URL is being passed to `decodeURIComponent` is an invalid URL format.

Here is my config/plugins.js
![image](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/55272632/57e0d227-99e6-4d2f-889a-03ef110b82bf)

**Comment by mattmilburn** [comment]
Hi again @trungnouden1108 Thank you for that perfect example text with the `%` character 🙌🏻 

The plugin is now upgraded to [version 2.2.1](https://github.com/mattmilburn/strapi-plugin-preview-button/releases/tag/v2.2.1) which should resolve your issue. Let me know how it goes for you! 👍🏻
