### ISSUE TITLE
Preview Button not showing in plugins after deployment

### ISSUE THREAD

**Issue by michaltalaga** [mattmilburn/strapi-plugin-preview-button#131]
I've tried everythign by now.

Works on my machine. Works on my machine in both in development and production mode pointing to production database. Works on my machine with both: strapi develop and strapi build & strapi start
![image](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/10220151/47d3b24a-f1a3-455a-996e-aa29050e6528)

does not work when i deploy
![image](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/10220151/d0e8353e-8547-4152-8e92-25ba88218fc6)

plugin doesn't even show on the list. BUT!!!
it does show as installed in marketplace
![image](https://github.com/mattmilburn/strapi-plugin-preview-button/assets/10220151/35edf45c-8343-4aa3-a87b-486302b81cc7)

package.json
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@strapi/design-system": "^1.13.1",
    "@strapi/icons": "^1.13.1",
    "@strapi/plugin-color-picker": "4.20.2",
    "@strapi/plugin-i18n": "4.20.2",
    "@strapi/plugin-seo": "^1.9.8",
    "@strapi/plugin-users-permissions": "4.20.2",
    "@strapi/strapi": "4.20.2",
    "pg": "^8.11.3",
    "pg-connection-string": "^2.6.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^5.3.4",
    "strapi-plugin-country-select": "^1.0.3",
    "strapi-plugin-preview-button": "^2.2.2",
    "strapi-plugin-redirects": "^0.0.6",
    "strapi-plugin-sitemap": "^3.0.6",
    "strapi-provider-upload-do": "^3.6.9",
    "styled-components": "^5.3.11"
  },
  "overrides": {
    "strapi-plugin-redirects": {
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "styled-components": "^5.3.11"
    }
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "72a64498-6701-403f-ae9f-d29f78a45ad4"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

//./config/plugins.js
'use strict';

module.exports = {
  'preview-button': {
    config: {
      contentTypes: [
        {
          uid: 'api::post.post',
          draft: {
            url: 'https://site.com/articles/preview/{slug}',
            query: {
              "preview": "preview"
            }
          },
        },
      ],
    },
  }
}

**Comment by mattmilburn** [comment]
Hi @michaltalaga That is certainly weird and it suggests an issue with either a deployment configuration or one of your other dependencies. Have you tried deploying without some of the custom plugins installed? I'm not 100% sure what would be happening without troubleshooting your app and deployment.
