### ISSUE TITLE
Please release strapi v5 compatible version

### ISSUE THREAD

**Issue by Sagar-echo** [mattmilburn/strapi-plugin-preview-button#143]
Error: Could not load js config file                                

```
/Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/strapi-plugin-preview-button/strapi-server.js: Cannot find module'@strapi/utils'
                                                Require stack:                                                 - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/strapi-plugin-preview-button/server/config.js                  - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/strapi-plugin-preview-button/server/index.js                   - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/strapi-plugin-preview-button/strapi-server.js                  - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/node_modules/@strapi/utils/dist/index.js          - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/configuration/urls.js                        - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/configuration/index.js                       - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/Strapi.js                                    - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/index.js                                     - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/strapi/dist/cli/commands/admin/create-user.js          - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/strapi/dist/cli/commands/index.js                      - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/strapi/dist/cli/index.js                               - /Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/strapi/bin/strapi.js                                   at loadJsFile (/Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/utils/load-config-file.js:18:13)at Module.loadConfigFile                                       (/Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/utils/load-config-file.js:37:14)              at loadPlugins (/Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/loaders/plugins/index.js:118:41) at async Promise.all (index 3)                                 at async Module.loadApplicationContext                         (/Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/loaders/index.js:12:3)                        at async Object.register                                       (/Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/providers/registries.js:26:5)                 at async Strapi.register (/Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/Strapi.js:322:7)     at async Strapi.load (/Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/core/dist/Strapi.js:314:5)         at async Module.develop                                        (/Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/strapi/dist/node/develop.js:177:28)                     at async action (/Users/sagar.ahuja/Downloads/ackontent-cms/strapi/node_modules/@strapi/strapi/dist/cli/commands/develop.js:18:5)                                                               

```

**Comment by rohit-smartshore** [comment]
Error:

polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/helper-plugin"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/index.js:1:41:
polaramp-website-strapi-1  |       1 │ import { prefixPluginTranslations } from '@strapi/helper-plugin';
polaramp-website-strapi-1  |         ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/helper-plugin" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] The JSX syntax extension is not currently enabled
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/contentManagerHooks/add-preview-column.js:33:33:
polaramp-website-strapi-1  |       33 │         cellFormatter: (data) => <ListViewColumn data={data} layou...
polaramp-website-strapi-1  |          ╵                                  ^
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] The JSX syntax extension is not currently enabled
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/CopyLinkButton/index.js:26:4:
polaramp-website-strapi-1  |       26 │     <CopyToClipboard text={url} onCopy={handleOnCopy}>
polaramp-website-strapi-1  |          ╵     ^
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] The JSX syntax extension is not currently enabled
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/PreviewButton/index.js:26:4:
polaramp-website-strapi-1  |       26 │     <Button
polaramp-website-strapi-1  |          ╵     ^
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] The JSX syntax extension is not currently enabled
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/ListViewColumn/index.js:63:6:
polaramp-website-strapi-1  |       63 │       <Flex {...stopPropagation}>
polaramp-website-strapi-1  |          ╵       ^
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] The JSX syntax extension is not currently enabled
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/PreviewButtonGroup/index.js:14:4:
polaramp-website-strapi-1  |       14 │     <>
polaramp-website-strapi-1  |          ╵     ^
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] The JSX syntax extension is not currently enabled
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/EditViewRightLinks/index.js:27:4:
polaramp-website-strapi-1  |       27 │     <>
polaramp-website-strapi-1  |          ╵     ^
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   The esbuild loader for this file is currently set to "js" but it must be set to "jsx" to be able to parse JSX syntax. You can use "loader: { '.js': 'jsx' }" to do that.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/helper-plugin"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/EditViewRightLinks/index.js:2:41:
polaramp-website-strapi-1  |       2 │ import { useCMEditViewDataManager } from '@strapi/helper-plugin';
polaramp-website-strapi-1  |         ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/helper-plugin" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/design-system/Flex"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/ListViewColumn/index.js:6:21:
polaramp-website-strapi-1  |       6 │ import { Flex } from '@strapi/design-system/Flex';
polaramp-website-strapi-1  |         ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/design-system/Flex" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/helper-plugin"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/hooks/use-preview-button.js:2:29:
polaramp-website-strapi-1  |       2 │ import { useStrapiApp } from '@strapi/helper-plugin';
polaramp-website-strapi-1  |         ╵                              ~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/helper-plugin" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/design-system/Button"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/CopyLinkButton/index.js:5:23:
polaramp-website-strapi-1  |       5 │ import { Button } from '@strapi/design-system/Button';
polaramp-website-strapi-1  |         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/design-system/Button" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/design-system/Button"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/PreviewButton/index.js:4:23:
polaramp-website-strapi-1  |       4 │ import { Button } from '@strapi/design-system/Button';
polaramp-website-strapi-1  |         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/design-system/Button" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/design-system/IconButton"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/ListViewColumn/index.js:7:27:
polaramp-website-strapi-1  |       7 │ import { IconButton } from '@strapi/design-system/IconButton';
polaramp-website-strapi-1  |         ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/design-system/IconButton" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/helper-plugin"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/CopyLinkButton/index.js:6:32:
polaramp-website-strapi-1  |       6 │ import { useNotification } from '@strapi/helper-plugin';
polaramp-website-strapi-1  |         ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/helper-plugin" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/helper-plugin"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/hooks/use-plugin-config.js:3:68:
polaramp-website-strapi-1  |       3 │ ...er, useFetchClient, useNotification } from '@strapi/helper-plugin';
polaramp-website-strapi-1  |         ╵                                               ~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/helper-plugin" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Missing "./ExternalLink" specifier in "@strapi/icons" package [plugin vite:dep-pre-bundle]
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/PreviewButton/index.js:5:25:
polaramp-website-strapi-1  |       5 │ import ExternalLink from '@strapi/icons/ExternalLink';
polaramp-website-strapi-1  |         ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   This error came from the "onResolve" callback registered here:
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/esbuild/lib/main.js:1293:20:
polaramp-website-strapi-1  |       1293 │       let promise = setup({
polaramp-website-strapi-1  |            ╵                     ^
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     at setup (file:///app/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:49762:19)
polaramp-website-strapi-1  |     at handlePlugins (/app/node_modules/esbuild/lib/main.js:1293:21)
polaramp-website-strapi-1  |     at buildOrContextImpl (/app/node_modules/esbuild/lib/main.js:979:5)
polaramp-website-strapi-1  |     at Object.buildOrContext (/app/node_modules/esbuild/lib/main.js:788:5)
polaramp-website-strapi-1  |     at /app/node_modules/esbuild/lib/main.js:2224:68
polaramp-website-strapi-1  |     at new Promise (<anonymous>)
polaramp-website-strapi-1  |     at Object.context (/app/node_modules/esbuild/lib/main.js:2224:27)
polaramp-website-strapi-1  |     at Object.context (/app/node_modules/esbuild/lib/main.js:2048:58)
polaramp-website-strapi-1  |     at prepareEsbuildOptimizerRun (file:///app/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:53971:35)
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/design-system/Loader"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/ListViewColumn/index.js:8:23:
polaramp-website-strapi-1  |       8 │ import { Loader } from '@strapi/design-system/Loader';
polaramp-website-strapi-1  |         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/design-system/Loader" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Missing "./Link" specifier in "@strapi/icons" package [plugin vite:dep-pre-bundle]
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/CopyLinkButton/index.js:7:21:
polaramp-website-strapi-1  |       7 │ import LinkIcon from '@strapi/icons/Link';
polaramp-website-strapi-1  |         ╵                      ~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   This error came from the "onResolve" callback registered here:
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/esbuild/lib/main.js:1293:20:
polaramp-website-strapi-1  |       1293 │       let promise = setup({
polaramp-website-strapi-1  |            ╵                     ^
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     at setup (file:///app/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:49762:19)
polaramp-website-strapi-1  |     at handlePlugins (/app/node_modules/esbuild/lib/main.js:1293:21)
polaramp-website-strapi-1  |     at buildOrContextImpl (/app/node_modules/esbuild/lib/main.js:979:5)
polaramp-website-strapi-1  |     at Object.buildOrContext (/app/node_modules/esbuild/lib/main.js:788:5)
polaramp-website-strapi-1  |     at /app/node_modules/esbuild/lib/main.js:2224:68
polaramp-website-strapi-1  |     at new Promise (<anonymous>)
polaramp-website-strapi-1  |     at Object.context (/app/node_modules/esbuild/lib/main.js:2224:27)
polaramp-website-strapi-1  |     at Object.context (/app/node_modules/esbuild/lib/main.js:2048:58)
polaramp-website-strapi-1  |     at prepareEsbuildOptimizerRun (file:///app/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:53971:35)
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Could not resolve "@strapi/helper-plugin"
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/ListViewColumn/index.js:9:49:
polaramp-website-strapi-1  |       9 │ ... { stopPropagation, useNotification } from '@strapi/helper-plugin';
polaramp-website-strapi-1  |         ╵                                               ~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   You can mark the path "@strapi/helper-plugin" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Missing "./ExternalLink" specifier in "@strapi/icons" package [plugin vite:dep-pre-bundle]
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/ListViewColumn/index.js:10:25:
polaramp-website-strapi-1  |       10 │ import ExternalLink from '@strapi/icons/ExternalLink';
polaramp-website-strapi-1  |          ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   This error came from the "onResolve" callback registered here:
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/esbuild/lib/main.js:1293:20:
polaramp-website-strapi-1  |       1293 │       let promise = setup({
polaramp-website-strapi-1  |            ╵                     ^
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     at setup (file:///app/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:49762:19)
polaramp-website-strapi-1  |     at handlePlugins (/app/node_modules/esbuild/lib/main.js:1293:21)
polaramp-website-strapi-1  |     at buildOrContextImpl (/app/node_modules/esbuild/lib/main.js:979:5)
polaramp-website-strapi-1  |     at Object.buildOrContext (/app/node_modules/esbuild/lib/main.js:788:5)
polaramp-website-strapi-1  |     at /app/node_modules/esbuild/lib/main.js:2224:68
polaramp-website-strapi-1  |     at new Promise (<anonymous>)
polaramp-website-strapi-1  |     at Object.context (/app/node_modules/esbuild/lib/main.js:2224:27)
polaramp-website-strapi-1  |     at Object.context (/app/node_modules/esbuild/lib/main.js:2048:58)
polaramp-website-strapi-1  |     at prepareEsbuildOptimizerRun (file:///app/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:53971:35)
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | ✘ [ERROR] Missing "./Link" specifier in "@strapi/icons" package [plugin vite:dep-pre-bundle]
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/strapi-plugin-preview-button/admin/src/components/ListViewColumn/index.js:11:21:
polaramp-website-strapi-1  |       11 │ import LinkIcon from '@strapi/icons/Link';
polaramp-website-strapi-1  |          ╵                      ~~~~~~~~~~~~~~~~~~~~
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |   This error came from the "onResolve" callback registered here:
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     node_modules/esbuild/lib/main.js:1293:20:
polaramp-website-strapi-1  |       1293 │       let promise = setup({
polaramp-website-strapi-1  |            ╵                     ^
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  |     at setup (file:///app/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:49762:19)
polaramp-website-strapi-1  |     at handlePlugins (/app/node_modules/esbuild/lib/main.js:1293:21)
polaramp-website-strapi-1  |     at buildOrContextImpl (/app/node_modules/esbuild/lib/main.js:979:5)
polaramp-website-strapi-1  |     at Object.buildOrContext (/app/node_modules/esbuild/lib/main.js:788:5)
polaramp-website-strapi-1  |     at /app/node_modules/esbuild/lib/main.js:2224:68
polaramp-website-strapi-1  |     at new Promise (<anonymous>)
polaramp-website-strapi-1  |     at Object.context (/app/node_modules/esbuild/lib/main.js:2224:27)
polaramp-website-strapi-1  |     at Object.context (/app/node_modules/esbuild/lib/main.js:2048:58)
polaramp-website-strapi-1  |     at prepareEsbuildOptimizerRun (file:///app/node_modules/vite/dist/node/chunks/dep-p3C6MpSJ.js:53971:35)
polaramp-website-strapi-1  | 
polaramp-website-strapi-1  | 8:25:51 AM [vite] error while updating dependencies:
polaramp-website-strapi-1  | Error: Build failed with 21 errors:
polaramp-website-strapi-1  | node_modules/strapi-plugin-preview-button/admin/src/components/CopyLinkButton/index.js:5:23: ERROR: Could not resolve "@strapi/design-system/Button"
polaramp-website-strapi-1  | node_modules/strapi-plugin-preview-button/admin/src/components/CopyLinkButton/index.js:6:32: ERROR: Could not resolve "@strapi/helper-plugin"
polaramp-website-strapi-1  | node_modules/strapi-plugin-preview-button/admin/src/components/CopyLinkButton/index.js:7:21: ERROR: [plugin: vite:dep-pre-bundle] Missing "./Link" specifier in "@strapi/icons" package
polaramp-website-strapi-1  | node_modules/strapi-plugin-preview-button/admin/src/components/CopyLinkButton/index.js:26:4: ERROR: The JSX syntax extension is not currently enabled
polaramp-website-strapi-1  | node_modules/strapi-plugin-preview-button/admin/src/components/EditViewRightLinks/index.js:2:41: ERROR: Could not resolve "@strapi/helper-plugin"
polaramp-website-strapi-1  | ...
polaramp-website-strapi-1  |     at failureErrorWithLog (/app/node_modules/esbuild/lib/main.js:1651:15)
polaramp-website-strapi-1  |     at /app/node_modules/esbuild/lib/main.js:1059:25
polaramp-website-strapi-1  |     at /app/node_modules/esbuild/lib/main.js:1527:9
polaramp-website-strapi-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by amogs4165** [comment]
++

**Comment by mzane42** [comment]
We are waiting too

**Comment by kaanmertkoc** [comment]
Anyone interest in this? Plan to make a migration fork for this package? If anyone is interested can give link when it is up.

**Comment by mattmilburn** [comment]
Closing this because there is no further action to take.
