### ISSUE TITLE
add "uid" parameter info before-build-url hook

### ISSUE THREAD

**Issue by pimpelsang** [mattmilburn/strapi-plugin-preview-button#145]
If you have multiple entities with custom preview logic in hook there is no way to know of which entity hook is running.

```
// from example code
app.registerHook('plugin/preview-button/before-build-url', ({ data, draft, published }) => {
// for which entity uid?
});
```

**Comment by mattmilburn** [comment]
Hi @pimpelsang This feature is now available in the latest version 3 of this plugin. However, this version will require upgrading to Strapi v5.
