### ISSUE TITLE
Dynamic links for live versions of Blog Posts.

### ISSUE THREAD

**Issue by WickedDeveloper** [mattmilburn/strapi-plugin-preview-button#17]
Is it possible to set dynamic URLs for Blog Posts vs. hard coding basePath = "blog"? For example, I have a blogSettings Single Type that sets the site-wide Blog root URL. Each blog post is based on this URL, for example - blog/post-1. However, the user has the ability to set the blog root URL to whatever they choose so I can't simply hard code this in plugins.js.

I was able to programmatically handle this in preview.js by writing logic based on the query.type being passed in. However, I am not sure if I can get around hard coding the basePath when using the published Object. In a perfect world, I would like to be able to set the basePath attribute to blogSettings.blogSlug (from the Single Type).

**Comment by WickedDeveloper** [comment]
For example, I would like to be able to express the basePath dynamically.

{
          uid: "api::social-hub-post.social-hub-post",
          targetField: "socialHub",
          draft: {
            query: {
              type: "socialHubPost",
            },
          },
          published: {
            basePath: "social",
          },
        },

**Comment by mattmilburn** [comment]
Hi @WickedDeveloper can I ask you to join the conversation at this similar/duplicate issue https://github.com/mattmilburn/strapi-plugin-preview-button/issues/18?

Seems like this is not an isolated request 🙂
