### ISSUE TITLE
Support multiple targetFields (or locale support)

### ISSUE THREAD

**Issue by zrothauser** [mattmilburn/strapi-plugin-preview-button#18]
I'm working on a project with i18n, where it would be useful to provide a locale to the preview URL in addition to a slug. 

I wonder if it might be helpful for others if the `targetField` option could support more than one field which is included for the front-end query - in my case it would be `slug` and `locale` - so that a config such as this:

```
'preview-button': {
  enabled: true,
  config: {
    contentTypes: [
      {
        uid: 'api::page.page',
        targetField: ['slug', 'locale'],
      },
    ],
  },
},
```

would result in a URL:
`http://example.com/api/preview?slug=your-page&locale=en&secret=YOURSECRET`

**Comment by mattmilburn** [comment]
@muhzain Please see my comments above. If I'm understanding correctly, it looks like you are wanting every param of the config to be dynamic. Can you provide more details on this scenario?

**Comment by zrothauser** [comment]
@mattmilburn Your plan makes sense to me. And at least for my use case, the query string isn't needed for the published URLs.

**Comment by slangeder** [comment]
Hi,

I've extended the plugin for our company's needs (really easy by overriding the findOne function) and could create a PR if you are interested.

The path configuration accepts placeholders with double curly braces like this `/{{locale}}/c/{{slug}}/{{id}}` and replaces them with the corresponding entity fields.

**Comment by javlund** [comment]
> Hi,
> 
> I've extended the plugin for our company's needs (really easy by overriding the findOne function) and could create a PR if you are interested.
> 
> The path configuration accepts placeholders with double curly braces like this `/{{locale}}/c/{{slug}}/{{id}}` and replaces them with the corresponding entity fields.
> 
> The proposal above wouldn't work for us since we have the namespace after the locale in our urls.

This would be useful for our use case, too. We are in the same situation currently.

**Comment by mckennapaul27** [comment]
> Hi,
> 
> I've extended the plugin for our company's needs (really easy by overriding the findOne function) and could create a PR if you are interested.
> 
> The path configuration accepts placeholders with double curly braces like this `/{{locale}}/c/{{slug}}/{{id}}` and replaces them with the corresponding entity fields.
> 
> The proposal above wouldn't work for us since we have the namespace after the locale in our urls.

This would be really useful for us too. Would you be able to share your solution?

**Comment by slangeder** [comment]
I fixed it by overriding the findOne function in the preview-button controller:
```js
const pluginId = 'preview-button';

module.exports = (plugin) => {
  plugin.controllers['preview-button'].findOne = findOne;
  return plugin;
};

async function findOne(ctx) {
  const { uid, id } = ctx.request.params;

  const pluginService = getService('preview-button');
  const { contentTypes, baseUrl } = await pluginService.getConfig();
  const supportedType = contentTypes.find(type => type.uid === uid);

  // Collection types will find by the ID and single types do not.
  const findParams = id ? { where: { id } } : {};
  const entity = await strapi.query(uid).findOne(findParams);

  const urls = getPreviewUrls(baseUrl, entity, supportedType);

  ctx.send({ urls });
}

function getPreviewUrls(baseUrl, entity, contentType) {
  const { path } = contentType;
  const url = replacePlaceholders(baseUrl + path, entity);

  return {
    draftUrl: url,
    publishedUrl: url
  };
}

function replacePlaceholders(url, entity) {
  function replace(_, propertyName) {
    return entity[propertyName];
  }

  // Matches everything between double curly braces (https://stackoverflow.com/a/57117346/8059242)
  return url.replace(/{{(([^}][^}]?|[^}]}?)*)}}/g, replace);
}

const getService = name => {
  return strapi.plugin(pluginId).service(name);
};
```
(save the code to `src/extensions/preview-button/strapi-server.js`)

In our case draftUrl equals publishedUrl, if you need separate urls you have to adapt the getPreviewUrls function.

My plugin-config.js looks like this:
```js
module.exports = ({ env }) => ({
  'preview-button': {
    enabled: true,
    config: {
      baseUrl: 'https://www.oktav.com',
      contentTypes: [
        {
          uid: 'api::entity.entity',
          path: '/{{locale}}/asdf/{{slug}}?preview=' + env('PREVIEW_SECRET'),
        }
      ],
    },
  }
});
```

**Comment by mattmilburn** [comment]
Hi @zrothauser, been a while! The Strapi preview button plugin has been updated with breaking features and now supports localization in the URLs as well as other new features 👍🏻
