### ISSUE TITLE
Preview only published contents

### ISSUE THREAD

**Issue by scoch5** [mattmilburn/strapi-plugin-preview-button#20]
Hello,
is there a way to display the button only if the content is published and not also in draft?

Thanks
Dan

**Comment by mattmilburn** [comment]
Hi @scoch5 Currently this is not supported but you're not the only one asking for that feature. 👍🏻 

I will make sure to support this in a future release. I'm just now making my way back to this specific plugin for a new round of updates and fixes.

**Comment by mattmilburn** [comment]
Hi @scoch5 , been a while! The Strapi preview button plugin has been updated with breaking features and now supports disabling the preview button for draft and/or published mode among a few other new features. 👍🏻  All you need to do is omit the `draft` or `published` config from a content type in the plugin config.
