### ISSUE TITLE
Preview button crashes language change due to change in number of React hooks

### ISSUE THREAD

**Issue by javlund** [mattmilburn/strapi-plugin-preview-button#23]
If we have the button on a piece of content, and then switch language, the page goes blank and the following error shows up in the console:

```
main.9296bcc6.js:10278 Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ti (main.9296bcc6.js:10276:55391)
    at Object.Ka [as useRef] (main.9296bcc6.js:10276:58831)
    at p.useRef (main.9296bcc6.js:10307:5860)
    at $.default (main.9296bcc6.js:9880:5574)
    at h (main.9296bcc6.js:10224:16156)
    at M (main.9296bcc6.js:10224:16852)
    at Zu (main.9296bcc6.js:10276:54833)
    at Ds (main.9296bcc6.js:10276:64692)
    at Fc (main.9296bcc6.js:10280:10162)
    at Rc (main.9296bcc6.js:10280:992)
```

If you follow the link, you'll discover that the issue is due to "Rendered more hooks than during the previous render."

Skimming the code, a candidate for this problem could be here: https://github.com/mattmilburn/strapi-plugin-preview-button/blob/main/admin/src/components/Injector/index.js

Namely:
```js
  if ( ! shouldRender ) {
    return null;
  }

  const { data, isLoading } = usePreviewData( uid, id, [ initialData ] );
```

In this case, there's a risk that `null` will be returned, which means that `usePreviewData` is never called. React (for good reason) insists that hooks should never be conditionally run, hence the error.

One solution could be to have the hook return a load function instead of a result. Another is to introduce a `skip` variable like e.g. Apollo does in their `useQuery`, meaning that the hook is always called but could just do nothing if need be.

By the way, reloading the blank page makes it work again until you change language once again.

Looking forward to this plugin working with i18n content. :)

**Comment by mattmilburn** [comment]
Thank you for discovering and reporting this. I'll certainly address this in the next plugin release which should be coming through very soon 👍🏻

**Comment by mattmilburn** [comment]
Hi @javlund Can you provide more details on how to reproduce this issue? I'm not sure I'm going through the same steps you are to reach the error.

**Comment by javlund** [comment]
> Hi @javlund Can you provide more details on how to reproduce this issue? I'm not sure I'm going through the same steps you are to reach the error.

Hi @mattmilburn - thanks for looking into this. I can't make a video of it right now, but basically, this issue requires that the official Strapi i18n module is enabled.

Once this has happened, add an additional language and create a content type that supports i18n.

Now, it should be possible to reproduce the error by creating content for that type in one language, and then switching to the other language. Not sure if the content needs to be published first; ours was.

Let me know if that doesn't help you and I'll try to dog more into it when I'm in front of a workstation again.
