### ISSUE TITLE
Can not get the preview button to hit the endpoint (404 error)

### ISSUE THREAD

**Issue by ManniS987** [mattmilburn/strapi-plugin-preview-button#30]
I have installed the plugin, the button displays however when I click on it - I get a 404 error. Is there something other than the mentions in the documentations that is required to be able to preview.

**Comment by nimame** [comment]
Same here.. In my dev env I've setup the following env vars:

```
STRAPI_PREVIEW_DRAFT_URL=http://localhost:1337/api/preview
STRAPI_PREVIEW_PUBLISHED_URL=http://localhost:8000
STRAPI_PREVIEW_SECRET=12345
```

In `config/plugins.js` I have:

```js
  'preview-button': {
    enabled: true,
    config: {
      contentTypes: [
        {
          uid: 'api::page.page',
          targetField: ['locale', 'slug'],
        },
        {
          uid: 'api::article.article',
          targetField: 'slug',
        },
      ],
    },
  },
```

I have created an `article` in draft mode with slug "sample-article", but calling the following URL gives a 404:

```
http://localhost:1337/api/preview?secret=12345&slug=sample-article
```

What are we missing?

**Comment by mattmilburn** [comment]
@ManniS987 I can't help diagnose your issue without more information. Can you provide me details like Strapi version and plugin version you are using? Also what kind of frontend app are you using alongside Strapi?

**Comment by mattmilburn** [comment]
@nimame Your environment vars are linking to Strapi instead of another frontend app. Your vars should probably look more like this below.

```bash
STRAPI_PREVIEW_DRAFT_URL=http://localhost:3000/api/preview
STRAPI_PREVIEW_PUBLISHED_URL=http://localhost:3000
```

In this case, I'm using Next.js which is running on port `3000` but Strapi runs on port `8000` and Strapi's API is using port `1337`.
