### ISSUE TITLE
Support configuration for buttons - allow to show only draft preview, only live preview, or both previews (current behavior)

### ISSUE THREAD

**Issue by manvydasu** [mattmilburn/strapi-plugin-preview-button#35]
Plugin lacks support for configurable buttons. There are cases, when Live Preview is not needed (or the opposite scenario, when Draft Preview is not needed). 

Configuration could be extended to include some options such as `disableDraftPreview` and `disableLivePreview`

Edit: This issue is similar to https://github.com/mattmilburn/strapi-plugin-preview-button/issues/20 I believe.

**Comment by mattmilburn** [comment]
Hi @manvydasu Thanks for raising this issue. I will certainly include this in an upcoming release. Hopefully this week some time. 🙂

**Comment by mattmilburn** [comment]
Hi @manvydasu The Strapi preview button plugin has recently been updated with breaking changes and also the ability to disable the preview button in either draft or published mode by simply omitting the `draft` or `published` configs from your plugin configuration. 👍🏻
