### ISSUE TITLE
[Feature] Preview button in List View

### ISSUE THREAD

**Issue by SalahAdDin** [mattmilburn/strapi-plugin-preview-button#38]
Hello,

Thanks for this plugin currently working in Strapi 4.

I would like to know if is possible to show the preview button(with an eye icon for example) and how can we do that.
![image](https://user-images.githubusercontent.com/5034215/182567763-ef333675-0cf8-4de0-8cd8-8e5122f2b06d.png)

If it is not an available feature, I would like to suggest reviewing [this plugin](https://github.com/danestves/strapi-plugin-preview-content) which supports this feature but is not migrated to version four.

Thank you

**Comment by mattmilburn** [comment]
Hi @SalahAdDin This is a good idea 👍🏻  I will keep this pinned for now and will try to include this in an upcoming release 🙂

**Comment by SalahAdDin** [comment]
> Hi @SalahAdDin This is a good idea 👍🏻 I will try to include this in an upcoming release 🙂

Cool!!! Thank you!

**Comment by SalahAdDin** [comment]
Why did you remove the feature label?

**Comment by mattmilburn** [comment]
Hi @SalahAdDin The Strapi preview button plugin has recently been updated with breaking changes and also features a new column in list view with the preview and "copy link" buttons among other new features.

The only downside is there is not currently a way in Strapi to add more icon buttons into the actions column on the far right. So the best solution for now is to add them into their own column and provide a config option to disable the column using `injectListViewColumn ` if it is undesired.

Thanks again for this suggestion! 🎉

**Comment by SalahAdDin** [comment]
> Hi @SalahAdDin The Strapi preview button plugin has recently been updated with breaking changes and also features a new column in the list view with the preview and "copy link" buttons among other new features.
> 
> The only downside is there is not currently a way in Strapi to add more icon buttons into the actions column on the far right. So the best solution, for now, is to add them into their own column and provide a config option to disable the column using `injectListViewColumn` if it is undesired.
> 
> Thanks again for this suggestion! 🎉

This is very good news.

I guess the changes for the new Strapi version in the dashboard disabled a way to add new buttons in the action Columns, right? Cause, for the 3 versions, as I showed in the referenced plugin, it was possible.

**Comment by mattmilburn** [comment]
@SalahAdDin This is true. Strapi v3 allowed developers to extend or override any of the core files from Strapi while v4 does not allow this. Instead we have to use plugins, middleware, and hooks to make customizations. Currently Strapi does not have a hook to add actions to the actions column.

**Comment by SalahAdDin** [comment]
> @SalahAdDin This is true. Strapi v3 allowed developers to extend or override any of the core files from Strapi while v4 does not allow this. Instead, we have to use plugins, middleware, and hooks to make customizations. Currently, Strapi does not have a hook to add actions to the actions column.

Can we ask for such a feature? where?
