### ISSUE TITLE
[Feature] Add "Share Link" functionality

### ISSUE THREAD

**Issue by kuli00** [mattmilburn/strapi-plugin-preview-button#39]
Hi,

There would be nice to add functionality to create a link to preview environment and share it with somebody.

I've found this useful in a case where you are working on a page, and you need do show somebody an article or page (without publishing it) who hasn't got access to strapi.

I know that to make this the `PREVIEW_SECRET` will no longer be a secret, but maybe there is other option?

**Comment by mattmilburn** [comment]
Hi @kuli00 Based on your suggestion, I think I will be making the `PREVIEW_SECRET` optional in an upcoming release 👍🏻

**Comment by mattmilburn** [comment]
Hi @kuli00 The Strapi preview button plugin has recently updated with breaking changes and includes a new "copy link" button which can be disabled if desired. The secret key and env vars are all optional as well. In reality, the secret key was never really a secret. 😄 

Thank you for this feature request! 🎉
