### ISSUE TITLE
Button not display for single-types

### ISSUE THREAD

**Issue by WebMamba** [mattmilburn/strapi-plugin-preview-button#40]
Hey folks! I have the plugin installed here is my package.json : 

> "dependencies": {
    "@strapi/plugin-i18n": "4.3.2",
    "@strapi/plugin-users-permissions": "4.3.2",
    "@strapi/strapi": "4.3.2",
    "better-sqlite3": "7.4.6",
    "dotenv": "^16.0.1",
    "find-config": "^1.0.0",
    "mysql": "^2.18.1",
    "strapi-plugin-preview-button": "^0.3.5"
  },

and I added the following configuration in ./config/plugins.js

`module.exports = {
  'preview-button': {
    config: {
      contentTypes: [
        {
          uid: 'api::home-page.home-page'
        }
      ]
    }
  }
}`

But the button in never display. Do i miss something in the de docs ?

**Comment by mattmilburn** [comment]
Hi @WebMamba I think you may still need to configure env vars for the plugin. [You can read about it in the docs here.](https://github.com/mattmilburn/strapi-plugin-preview-button#-requirements)

In a future release, these env vars will become optional 👍🏻 

Let me know how this works out for you.

**Comment by WebMamba** [comment]
No I already configure my envs. Here is my .env file : 

> STRAPI_PREVIEW_DRAFT_URL=http://localhost:1337/api/preview
STRAPI_PREVIEW_PUBLISHED_URL=http://localhost:8000
STRAPI_PREVIEW_SECRET=12345

**Comment by mattmilburn** [comment]
@WebMamba Okay I see the issue now. I actually thought this issue had been resolved before 🤔  Anyway, I will be working on a bug fix for this today 👍🏻  Thank you for raising this issue!

**Comment by mattmilburn** [comment]
@WebMamba This should be resolved now in the latest version [v0.3.6](https://github.com/mattmilburn/strapi-plugin-preview-button/releases/tag/v0.3.6)

Please let me know how this works out for you 🙂

**Comment by WebMamba** [comment]
@mattmilburn thanks for your work! It's working great now! But I looked at your correction, that was a silly bug! Maybe you can do an issue to the strapi repo, it doesn't look like the expected behaviour. 🤔
