### ISSUE TITLE
Usage with url-alias plugin

### ISSUE THREAD

**Issue by Alexnortung** [mattmilburn/strapi-plugin-preview-button#41]
Currently when using this plugin with url-alias it is not possible to use `url_alias` as the target field since it is not added when preview button tries to find the entity.
I have made a draft where one can provide a function and populate the entity themselves in https://github.com/Oak-Digital/strapi-plugin-preview-button/commit/2795726a9890f43d7ca68ac3335a21f648197ea2

However this might not be optimal, so could there be any other way to make this work?

**Comment by mattmilburn** [comment]
Hi @Alexnortung The Strapi preview button plugin has recently been updated with breaking changes and may help solve your issue. I have not tested with the url-alias plugin but the way the preview URLs are handled in v1.0.0 is completely new and allows any string or number param from the entry data to be parsed into the URL using `{curly_braces}`.

See the README section [Mapping values from entry data into preview URLs](https://github.com/mattmilburn/strapi-plugin-preview-button#mapping-values-from-entry-data-into-preview-urls) for details.

**Comment by Alexnortung** [comment]
Thanks, I will try it out!
