### ISSUE TITLE
strapi v4 preview button configuration

### ISSUE THREAD

**Issue by kiscdbc** [mattmilburn/strapi-plugin-preview-button#45]
Hej Matt, 
to which file do i have to add 

module.exports = {
  'preview-button': {
    config: {
      contentTypes: [
        ...
      ],
    },
  },
};

Thanks in advance!

**Comment by mattmilburn** [comment]
Hi @kiscdbc You need to create a file at `./config/plugins.js` for this code. You can read more about it in the [Strapi docs here](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/plugins.html).

I will be adding a note about this in the plugin documentation soon 👍🏻
