### ISSUE TITLE
How to override admin interface of plugin extension? 

### ISSUE THREAD

**Issue by Ruixian1006** [mattmilburn/strapi-plugin-preview-button#50]
I’m trying to customize one of the hooks file \src\extensions\preview-button\admin\src\hooks\use-preview-data.js but I’m not sure how to override the file with [plugin extension](https://docs.strapi.io/developer-docs/latest/development/plugins-extension.html#extending-a-plugin-s-content-types). The documentation only show the method for plugin’s server interface but I’m not sure how to customize for admin interface. Anyone know how to solve this ?

**Comment by mattmilburn** [comment]
Hi @Ruixian1006 To my knowledge, there is not a way to override the admin interface. However, the plugin has recently updated with breaking changes that you should review. Depending on what you are trying to accomplish, the new plugin options may help.
