### ISSUE TITLE
npm install error (peer dependency conflict)

### ISSUE THREAD

**Issue by samzlab** [mattmilburn/strapi-plugin-preview-button#56]
# npm install error

![image](https://user-images.githubusercontent.com/11741999/193207464-07574a4b-5a6d-4390-bba8-d05712539068.png)

## versions
**Strapi**: 4.4.0
**node**: v16.17.0
**npm**: 8.15.0

## reproduction
* `npx create-strapi-app@latest my-project --quickstart`
* `npm i strapi-plugin-preview-button@latest`

## workaround

Yes, using the `--force` flag on install

**Comment by mattmilburn** [comment]
Hi @samzlab I'm unable to reproduce this issue after meeting all of the specs you provided. Can you provide more details of your `package.json`? I feel like there is a conflicting dependency that I don't know about.

**Comment by samzlab** [comment]
```json
{
  "name": "strapi-test",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-documentation": "^4.4.0",
    "@strapi/plugin-i18n": "4.4.0",
    "@strapi/plugin-users-permissions": "4.4.0",
    "@strapi/strapi": "4.4.0",
    "better-sqlite3": "7.4.6",
    "strapi-plugin-preview-button": "^1.0.0",
    "strapi-plugin-publisher": "^1.1.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "acb7cc1a-405b-4f27-aa3f-a717ad3e3b97"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```

The interesting part is that now, if i make a fresh project there is no conflict.

But can still reproduce the error with `npm ci`. Should i attach the `package-lock.json` aswell?

**Comment by samzlab** [comment]
Well, i just removed the publisher plugin and now it's stops conflicting (i realized late that the error message mentioned that plugin too).

So nvm, looks like it's not caused by the preview-button :) Sorry for wasting your time!

**Comment by mattmilburn** [comment]
@samzlab Glad you were able to resolve your issue! 🎉
