### ISSUE TITLE
Open preview page in new tab, instead of replacing already opened tab

### ISSUE THREAD

**Issue by Krak86** [mattmilburn/strapi-plugin-preview-button#60]
Is it possible to add possibility to open 'preview' page always in new tab (not just replace the opened tab)?

I think we can remove (or make optional) the `target` prop (`PREVIEW_WINDOW_NAME`) in  `window.open( url, PREVIEW_WINDOW_NAME );`

Code:
https://github.com/mattmilburn/strapi-plugin-preview-button/blob/staging/admin/src/components/PreviewButton/index.js#L19

**Comment by mattmilburn** [comment]
Hi @Krak86 This option seems reasonable. I will include this in an upcoming release 👍🏻

**Comment by mattmilburn** [comment]
@Krak86 There is a new release for v1.0.1 which includes a new `openTarget` config option that should help you out 👍🏻 You should set it to `_blank`. [Here it is described in the README](https://github.com/mattmilburn/strapi-plugin-preview-button/tree/main#opentarget).

**Comment by Krak86** [comment]
> @Krak86 There is a new release for v1.0.1 which includes a new `openTarget` config option that should help you out 👍🏻 You should set it to `_blank`. [Here it is described in the README](https://github.com/mattmilburn/strapi-plugin-preview-button/tree/main#opentarget).

Awesome, man! Many thanks 👍
