### ISSUE TITLE
Support for node 18.x.x?

### ISSUE THREAD

**Issue by Micka33** [mattmilburn/strapi-plugin-preview-button#74]
I just created a new strapi project on the latest version.  
The default package.json->engines looks like that:

```js
{
//...
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
//...
}
```

Currently `strapi-plugin-preview-button` has the following requirements in [package.json][0]:  

```js
{
//...
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
//...
}
```

Therefor, I had to install a node package manager, [`n`][1], in order to install `node/16.x.x` because I only had `node/19.2.0` on my machine. And I had to downgrade my own `package.json->engine->node` requirements from `18.x.x` to `16.x.x`.  
Hopefully, it is working fine, no issue.

Still, it would be nice if the upper node version requirements was following the strapi one.  

So I must ask:
- is there any reason to keep node version requirements at `16.x.x`?  
- is there any plan to bump it to `18.x.x`?

[0]: https://github.com/mattmilburn/strapi-plugin-preview-button/blob/aedbf6343a8bff52dd407627865e810d2ab3bcce/package.json#L30 (link to current package.json at time of this post)
[1]: https://www.npmjs.com/package/n (link to n package on npm)

**Comment by mattmilburn** [comment]
Hi @Micka33 This is now updated in the latest [version 1.1.0](https://github.com/mattmilburn/strapi-plugin-preview-button/releases/tag/v1.1.0) of the plugin. 👍🏻  Thanks again for raising this issue. 🎉
