### ISSUE TITLE
Plugin crash admin page in Strapi > 4.5.1

### ISSUE THREAD

**Issue by quentinsimon** [mattmilburn/strapi-plugin-preview-button#75]
Since I've upgraded my Strapi (I tried in every release higher than 4.5.1), the preview plugin makes my Strapi admin page crash
![image](https://user-images.githubusercontent.com/5383226/208875989-2a65074a-3127-4afc-9ebf-2691c338608b.png)

Here after,  you can find the error message I could find in my console
![image](https://user-images.githubusercontent.com/5383226/208876187-405b8a49-d060-4760-bf90-45ac29563ea2.png)

If I disable `preview-button` in my `config/plugin.js` file, everything is back to normal

Hope it could help you

**Comment by mattmilburn** [comment]
Hi @quentinsimon  The plugin recently updated to [version 1.1.0](https://github.com/mattmilburn/strapi-plugin-preview-button/releases/tag/v1.1.0). Can you try upgrading the plugin to see if this resolves your issue? If not can you provide more details on your `package.json` and plugins config.

**Comment by quentinsimon** [comment]
I've updated to latest version and it is working as expected :)
Thanks for the fix @mattmilburn
